<?php

namespace AppBundle\Repository;

/**
 * SubTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubTagRepository extends \Doctrine\ORM\EntityRepository
{
}
