# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Tag:
            class: AppBundle\Entity\Tag
            controller: AppBundle\Controller\TagController
            dsy:
                children_entity: SubTag
                children_title: Sub Tags
                children_fa_icon: fa-users
            # disabled_actions: ['show']
            list:
                title: menu.tags
                # dql_filter: "entity.deletedAt is null"
                sort: ['name', 'ASC']
                actions:
                    - { name: 'new'}
                    - { name: 'edit'}
                    - { name: 'delete'}
                    - { name: 'show'}
                fields:
                    - { property: 'name'}
                    - { property: 'children', label: 'Tags', template: '@dsarhoyaDSYEasyAdmin/Fields/children.html.twig' }
            search:
                fields: [name]
                sort: ['name', 'ASC']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'app.basic', icon: 'pencil' }
                    - { property: 'name', label: 'entity.property.name' }
